name: Delete Preview CDK on PR
on: 
  pull_request:
    types:
      - closed
jobs:
  preview:
    runs-on: ubuntu-latest
    environment: dev
    permissions:
      id-token: write
      contents: read
    steps:
      - uses: actions/checkout@v4.2.2
      - uses: denoland/setup-deno@v2
        with:
          deno-version: v1.2.1
      - uses: aws-actions/configure-aws-credentials@v4.0.2
        with:
          role-to-assume: ${{vars.AWS_OIDC_ROLE_ARN}}
          aws-region: us-east-1
      - run: ENV="pr-$PR_NUMBER" deno run -A npm:aws-cdk@^2.173.2 destroy --all --force
        env:
          PR_NUMBER: ${{ github.event.number }}
